# Generated by Django 5.2.16 on 2026-08-02 14:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField()),
                ('type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'channel_connections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField()),
                ('phone', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('stage', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeadCaptureLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setting_id', models.UUIDField(blank=True, db_column='lead_capture_settings_id', null=True)),
                ('workspace_id', models.UUIDField(blank=True, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('row_hash', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('channel_status', models.JSONField(blank=True, default=dict, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('workflow_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lead_capture_leads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeadCaptureSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(blank=True, null=True)),
                ('campaign_name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('sheet_url', models.URLField()),
                ('phone_column', models.CharField(blank=True, max_length=100, null=True)),
                ('name_column', models.CharField(blank=True, max_length=100, null=True)),
                ('email_column', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('template_language', models.CharField(default='en', max_length=50)),
                ('email_enabled', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.IntegerField(blank=True, default=587, null=True)),
                ('smtp_user', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True)),
                ('email_from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email_from', models.CharField(blank=True, max_length=255, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('email_title', models.CharField(blank=True, max_length=255, null=True)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('email_button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('email_button_url', models.URLField(blank=True, null=True)),
                ('email_footer', models.TextField(blank=True, null=True)),
                ('voice_enabled', models.BooleanField(default=False)),
                ('voice_agent_type', models.CharField(default='livekit', max_length=50)),
                ('voice_id', models.CharField(default='anushka', max_length=100)),
                ('voice_prompt', models.TextField(blank=True, null=True)),
                ('voice_agent_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lead_capture_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_id', models.UUIDField()),
                ('wamid', models.CharField(blank=True, max_length=255, null=True)),
                ('direction', models.CharField(default='outbound', max_length=50)),
                ('content', models.TextField()),
                ('status', models.CharField(default='sent', max_length=50)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoiceCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('agent_type', models.CharField(default='livekit', max_length=50)),
                ('voice_id', models.CharField(default='anushka', max_length=100)),
                ('status', models.CharField(default='ringing', max_length=50)),
                ('livekit_room_name', models.CharField(blank=True, max_length=255, null=True)),
                ('livekit_sip_call_id', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'voice_calls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('workspace_id', models.UUIDField()),
                ('status', models.CharField(default='active', max_length=50)),
                ('trigger_type', models.CharField(blank=True, max_length=100, null=True)),
                ('graph', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workflows',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(blank=True, null=True)),
                ('workflow_id', models.UUIDField()),
                ('contact_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=50)),
                ('context', models.JSONField(blank=True, default=dict, null=True)),
                ('current_node', models.CharField(blank=True, max_length=255, null=True)),
                ('wake_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_runs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowRunStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(blank=True, null=True)),
                ('run_id', models.UUIDField()),
                ('node_id', models.CharField(max_length=100)),
                ('node_type', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('input', models.JSONField(blank=True, default=dict, null=True)),
                ('output', models.JSONField(blank=True, default=dict, null=True)),
                ('credits_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workflow_run_steps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AICreditLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(unique=True)),
                ('balance', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_credit_ledgers',
            },
        ),
        migrations.CreateModel(
            name='AICreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField()),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_credit_transactions',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(unique=True)),
                ('plan_tier', models.CharField(max_length=50)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('status', models.CharField(default='active', max_length=50)),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('has_voice_addon', models.BooleanField(default=False)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workspace_subscriptions',
            },
        ),
    ]
