# Generated by Django 5.2.16 on 2026-08-13 21:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0002_workflow_trigger_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('template_language', models.CharField(default='en', max_length=50)),
                ('target_filters', models.JSONField(blank=True, default=dict, null=True)),
                ('components', models.JSONField(blank=True, default=list, null=True)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaigns',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='aicreditledger',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='aicredittransaction',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='workspacesubscription',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='workspacesubscription',
            old_name='razorpay_subscription_id',
            new_name='razorpay_order_id',
        ),
        migrations.AddField(
            model_name='aicredittransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='use_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='ai_credits_addon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aicreditledger',
            name='workspace_id',
            field=models.UUIDField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aicredittransaction',
            name='workspace_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='workspacesubscription',
            name='workspace_id',
            field=models.UUIDField(db_index=True, unique=True),
        ),
    ]
